'''
num=int(input('enter the value: '))
x=1
y=1
if(num>=1):
 for a in range(num):
   z=x+y
   print(z)
   x=y
   y=z


a=12345
print(a[::-1])
'''

'''
n=int(input('enter the value: '))
r=0
n1=n
for h in range(4):
    if(n1>0):
       a=n1%10
       r=(r*10)+a
       n1=n1//10
       
if(n==r):
        print('it is a palindrome')
else:
    print('it is not a palindrome')
'''

i=0
while(i<10):
    i+=1
    if(i==5):
        continue
    print(i)

    
    




        
