from tkinter import *
from tkinter import ttk,font,messagebox
from PIL import ImageTk,ImageTk,Image
import pymysql as mysql
import os

def studentregistration(win):
    win.destroy()
    win=Tk()
    win.geometry('500x500')
    win.attributes("-fullscreen",True)
    f1=Frame(win,width=1500,height=50,bg="orchid3")
    f1.pack()
    f2=Frame(win,width=3500,height=40)
    label_font=font.Font(weight="bold",family="Times New Roman",size=25)
    f2=Label(win,text="LIVE CARRIERS",font=label_font,bg="orchid3",fg="black",height=0)
    f2.place(relx=0.065,rely=0.001)
    img1=ImageTk.PhotoImage(Image.open("logoimage.jpg"))
    i1=Label(win,image=img1)
    i1.place(relx=0,rely=0)
    label_font=font.Font(weight="bold",family="Times New Roman",size=19)
    f2=Button(win,text="Home",font=label_font,bg="orchid3",fg="black")
    f2.place(relx=0.47,rely=0)
    f2=Button(win,text="Admin Login",font=label_font,bg="orchid3",fg="black",command=lambda:adminlogin(win))
    f2.place(relx=0.53,rely=0)
    f2=Button(win,text="Student Login",font=label_font,bg="orchid3",fg="black",command=lambda:studentlogin(win))
    f2.place(relx=0.65,rely=0)
    f2=Button(win,text="Staff Login",font=label_font,bg="orchid3",fg="black",command=lambda:stafflogin(win))
    f2.place(relx=0.77,rely=0)
    f2=Button(win,text="Courses",font=label_font,bg="orchid3",fg="black",command=lambda:courses(win))
    f2.place(relx=0.87,rely=0)
    f2=Button(win,text="Exit",font=label_font,bg="orchid3",fg="black",command=lambda:exit(win))
    f2.place(relx=0.95,rely=0)
    img=ImageTk.PhotoImage(Image.open("studentregimage.jpg"))
    canvas=Canvas(win)
    canvas.create_image(690,390,image=img)
    canvas.pack(fill="both",expand=True)
    label_font=font.Font(weight="bold",family="Helvetica",size=17)
    canvas.create_text(815,30,text="Name",fill="Black",font=label_font)
    canvas.create_text(817,89,text="Staff_ID",fill="Black",font=label_font)
    canvas.create_text(813,148,text="DOB",fill="Black",font=label_font)
    canvas.create_text(815,209,text="Gender",fill="Black",font=label_font)
    canvas.create_text(815,270,text="Email_ID",fill="Black",font=label_font)
    canvas.create_text(817,332,text="Contact",fill="Black",font=label_font)
    canvas.create_text(817,402,text="Course",fill="Black",font=label_font)
    canvas.create_text(810,462,text="Qualification",fill="Black",font=label_font)
    canvas.create_text(815,530,text="Address",fill="Black",font=label_font)
    name=Entry(win)
    name.place(relx=0.7,rely=0.09,width=200,height=30)
    staffid=Entry(win)
    staffid.place(relx=0.7,rely=0.16,width=200,height=30)
    dob=Entry(win)
    dob.place(relx=0.7,rely=0.24,width=200,height=30)
    var=IntVar()
    g1=Radiobutton(win,text="Male",variable=var,value=1)
    g1.place(relx=0.7,rely=0.33)
    g2=Radiobutton(win,text="Female",variable=var,value=2)
    g2.place(relx=0.75,rely=0.33)
    g3=Radiobutton(win,text="Others",variable=var,value=3)
    g3.place(relx=0.81,rely=0.33)
    e=Entry(win)
    e.place(relx=0.7,rely=0.4,width=200,height=30)
    c=Entry(win)
    c.place(relx=0.7,rely=0.48,width=200,height=30)
    course=ttk.Combobox(win,values=["Python","Machine Learning","Artificial Intelligence","DataScience","Fullstack Development","Ms-Office","Tally Prime","Advanced Excel","Java","Statistics","Software Testing","Blockchain Technology","C Programming","C++ Programming","Asp.net","Django","Robotics"])
    course.place(relx=0.7,rely=0.57,width=200,height=30)
    course.set("select the course")
    qualification=Entry(win)
    qualification.place(relx=0.7,rely=0.65,width=200,height=30)
    text=Text(win)
    text.place(relx=0.7,rely=0.72,width=300,height=100)

    def insert():
        connection=mysql.connect(host="localhost",password="livewire",database="subhanistudentregistration",user="root")
        cursor=connection.cursor()
        if(var.get()==1):
            gender="Male"
        elif(var.get()==2):
            gender="Female"
        else:
            gender="other"
        s="insert into studentregistrationtable03(name,staffid,dob,gender,email,contact,course,qualification,address) values (%s,%s,%s,%s,%s,%s,%s,%s,%s)"
        t=(name.get(),staffid.get(),dob.get(),gender,e.get(),c.get(),course.get(),qualification.get(),text.get("1.0",END))
        cursor.execute(s,t)
        connection.commit()
        messagebox.showinfo("student registration","insert successfully")

    def update():
        connection=mysql.connect(host="localhost",password="livewire",database="subhanistudentregistration",user="root")
        cursor=connection.cursor()
        sql="update studentregistrationtable03 set name='"+str(name.get())+"',staffid='"+str(staffid.get())+"',dob='"+str(dob.get())+"',gender='"+str(var.get())+"',email='"+str(e.get())+"',contact='"+str(c.get())+"',course='"+str(course.get())+"',qualification='"+str(qualification.get())+"',address='"+str(text.get("1.0",END))+"'where name='"+name.get()+"'"
        cursor.execute(sql)
        connection.commit() 
        messagebox.showinfo("student registration","update successfully")

    def delete():
        connection=mysql.connect(host="localhost",password="livewire",database="subhanistudentregistration",user="root")
        cursor=connection.cursor()
        sql="delete from studentregistrationtable03 where name='"+name.get()+"'"
        cursor.execute(sql)
        connection.commit()
        messagebox.showinfo("student registration","Delete successfully")

    ins=Button(win,text="Insert",command=lambda:insert(),font=label_font)
    ins.place(relx=0.70,rely=0.88)
    upd=Button(win,text="Update",command=lambda:update(),font=label_font)
    upd.place(relx=0.78,rely=0.88)
    Del=Button(win,text="Delete",command=lambda:delete(),font=label_font)
    Del.place(relx=0.87,rely=0.88)
    canvas.pack(fill="both",expand=True)
    label_font=font.Font(weight="bold",family="Times New Roman",size=15)
    copyf=Frame(win,width=1500,height=50,bg="orchid3")
    copyf.place(relx=0,rely=0.94) 
    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    copyf1=Label(win,text="@Copyrights 2024",font=label_font,bg="orchid3",fg="black")
    copyf1.place(relx=0.42,rely=0.94)
    win.mainloop()  

def staffregistration(win):
    win.destroy()
    win=Tk()
    win.geometry('500x500')
    win.attributes("-fullscreen",True)
    f1=Frame(win,width=1500,height=50,bg="orchid3")
    f1.pack()
    f2=Frame(win,width=3500,height=40)
    label_font=font.Font(weight="bold",family="Times New Roman",size=25)
    f2=Label(win,text="LIVE CARRIERS",font=label_font,bg="orchid3",fg="black",height=0)
    f2.place(relx=0.065,rely=0.001)
    img1=ImageTk.PhotoImage(Image.open("logoimage.jpg"))
    i1=Label(win,image=img1)
    i1.place(relx=0,rely=0)
    label_font=font.Font(weight="bold",family="Times New Roman",size=19)
    f2=Button(win,text="Home",font=label_font,bg="orchid3",fg="black")
    f2.place(relx=0.47,rely=0)
    f2=Button(win,text="Admin Login",font=label_font,bg="orchid3",fg="black",command=lambda:adminlogin(win))
    f2.place(relx=0.53,rely=0)
    f2=Button(win,text="Student Login",font=label_font,bg="orchid3",fg="black",command=lambda:studentlogin(win))
    f2.place(relx=0.65,rely=0)
    f2=Button(win,text="Staff Login",font=label_font,bg="orchid3",fg="black",command=lambda:stafflogin(win))
    f2.place(relx=0.77,rely=0)
    f2=Button(win,text="Courses",font=label_font,bg="orchid3",fg="black",command=lambda:courses(win))
    f2.place(relx=0.87,rely=0)
    f2=Button(win,text="Exit",font=label_font,bg="orchid3",fg="black",command=lambda:exit(win))
    f2.place(relx=0.95,rely=0)
    img=ImageTk.PhotoImage(Image.open("staffregimage.jpg"))
    canvas=Canvas(win)
    canvas.create_image(400,360,image=img)
    canvas.pack(fill="both",expand=True)
    label_font=font.Font(weight="bold",family="Helvetica",size=17)
    canvas.create_text(100,118,text="Name",fill="Black",font=label_font)
    canvas.create_text(100,175,text="DOB",fill="Black",font=label_font)
    canvas.create_text(100,243,text="Gender",fill="Black",font=label_font)
    canvas.create_text(100,310,text="Staff-ID",fill="Black",font=label_font)
    canvas.create_text(100,385,text="Email_ID",fill="Black",font=label_font)
    canvas.create_text(90,450,text="Designation",fill="Black",font=label_font)
    canvas.create_text(460,118,text="Field",fill="Black",font=label_font)
    canvas.create_text(470,175,text="Contact",fill="Black",font=label_font)
    canvas.create_text(490,239,text="Adhaar No",fill="Black",font=label_font)
    canvas.create_text(490,305,text="Department",fill="Black",font=label_font)
    canvas.create_text(475,385,text="Address",fill="Black",font=label_font)
    name=Entry(win)
    name.place(relx=0.13,rely=0.2,width=200,height=30)
    dob=Entry(win)
    dob.place(relx=0.13,rely=0.28,width=200,height=30)
    var=IntVar()
    g1=Radiobutton(win,text="Male",variable=var,value=1)
    g1.place(relx=0.13,rely=0.37)
    g2=Radiobutton(win,text="Female",variable=var,value=2)
    g2.place(relx=0.18,rely=0.37)
    g3=Radiobutton(win,text="Others",variable=var,value=3)
    g3.place(relx=0.24,rely=0.37)
    staffid=Entry(win)
    staffid.place(relx=0.13,rely=0.45,width=200,height=30)
    e=Entry(win)
    e.place(relx=0.13,rely=0.55,width=200,height=30)
    designation=Entry(win)
    designation.place(relx=0.13,rely=0.63,width=200,height=30)
    var1=IntVar()
    field=Radiobutton(win,text="Teaching",variable=var1,value=1)
    field.place(relx=0.43,rely=0.2)
    field1=Radiobutton(win,text="Non-Teaching",variable=var1,value=2)
    field1.place(relx=0.51,rely=0.2)
    contact=Entry(win)
    contact.place(relx=0.43,rely=0.28,width=200,height=30)
    adhaar=Entry(win)
    adhaar.place(relx=0.43,rely=0.36,width=200,height=30)
    department=Entry(win)
    department.place(relx=0.43,rely=0.45,width=200,height=30)
    text=Text(win)
    text.place(relx=0.43,rely=0.54,width=250,height=95)

    def insert():
        connection=mysql.connect(host="localhost",password="livewire",database="subhanistaffregistration",user="root")
        cursor=connection.cursor()
        if(var.get()==1):
            gender="Male"
        elif(var.get()==2):
            gender="Female"
        else:
            gender="other"

        if(var1.get()==1):
            field="Teaching"
        elif(var1.get()==2):
            field="Non-Teaching"
        
        s="insert into staffregistrationtable03(Name,DOB,Gender,Staffid,Emailid,Designation,Field,Contact,AdhaarNo,Department,Address) values (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"
        t=(name.get(),dob.get(),gender,staffid.get(),e.get(),designation.get(),field,contact.get(),adhaar.get(),department.get(),text.get("1.0",END))
        cursor.execute(s,t)
        connection.commit()
        messagebox.showinfo("Staff registration","Insert Successfully")

    def update():
        connection=mysql.connect(host="localhost",password="livewire",database="subhanistaffregistration",user="root")
        cursor=connection.cursor()
        if(var.get()==1):
            gender="Male"
        elif(var.get()==2):
            gender="Female"
        else:
            gender="other"

        if(var1.get()==1):
            field="Teaching"
        elif(var1.get()==2):
            field="Non-Teaching"

        sql="update staffregistrationtable03 set Name='"+str(name.get())+"',DOB='"+str(dob.get())+"',Gender='"+gender+"',Staffid='"+str(staffid.get())+"',Emailid='"+str(e.get())+"',Designation='"+str(designation.get())+"',Field='"+field+"',contact='"+str(contact.get())+"',AdhaarNo='"+str(adhaar.get())+"',Department='"+str(department.get())+"',Address='"+str(text.get("1.0",END))+"'where Name='"+name.get()+"'"
        cursor.execute(sql)
        connection.commit() 
        messagebox.showinfo("Staff registration","Update Successfully")

    def delete():
        connection=mysql.connect(host="localhost",password="livewire",database="subhanistaffregistration",user="root")
        cursor=connection.cursor()
        sql="delete from staffregistrationtable03 where Name='"+name.get()+"'"
        cursor.execute(sql)
        connection.commit()
        messagebox.showinfo("Staff registration","Delete Successfully")


    label_font=font.Font(weight="bold",family="Helvetica",size=15)
    ins=Button(win,text="Insert",command=lambda:insert(),font=label_font)
    ins.place(relx=0.2,rely=0.8)
    upd=Button(win,text="Update",command=lambda:update(),font=label_font)
    upd.place(relx=0.3,rely=0.8)
    Del=Button(win,text="Delete",command=lambda:delete(),font=label_font)
    Del.place(relx=0.4,rely=0.8)
    label_font=font.Font(weight="bold",family="Times New Roman",size=15)
    copyf=Frame(win,width=1500,height=50,bg="orchid3")
    copyf.place(relx=0,rely=0.94) 
    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    copyf1=Label(win,text="@Copyrights 2024",font=label_font,bg="orchid3",fg="black")
    copyf1.place(relx=0.42,rely=0.94)
    win.mainloop()

def adminloginhome(win):
    win.destroy()
    win=Tk()
    win.geometry('500x500')
    win.attributes('-fullscreen',True)
    f1=Frame(win,width=1500,height=60,bg="orchid3")
    f1.pack()
    f2=Frame(win,width=3500,height=60)
    label_font=font.Font(weight="bold",family="Times New Roman",size=30)
    f2=Label(win,text="LIVE CARRIERS",font=label_font,bg="orchid3",fg="black")
    f2.place(relx=0.4,rely=0.001)
    img1=ImageTk.PhotoImage(Image.open("logoimage.jpg"))
    i1=Label(win,image=img1)
    i1.place(relx=0.33,rely=0.005)
    label_font=font.Font(weight="bold",family="Tahoma",size=15)
    img=ImageTk.PhotoImage(Image.open("adminhomeimage.jpg"))
    canvas=Canvas(win)
    canvas.create_image(700,400,image=img)
    label_font=font.Font(weight="bold",family="Tahoma",size=18)
    t="""Our student registration form is an excellent solution for educational institutions aiming to 
        gather essential information about new students.By using this form, you'll be able
              to collect personal, academic, and additional relevant data all in one place."""
    canvas.create_text(720,300,text=t,fill="white",font=label_font)
    label_font=font.Font(weight="bold",family="Tahoma",size=15)
    b=Button(win,text="Student Registration",font=label_font,bg="green",fg="black",width=20,height=0,command=lambda:studentregistration(win))
    b.place(relx=0.3,rely=0.7)
    b1=Button(win,text="Staff Registration",font=label_font,bg="green",fg="black",width=20,height=0,command=lambda:staffregistration(win))
    b1.place(relx=0.55,rely=0.7)
    canvas.pack(fill="both",expand=True)
    copyf=Frame(win,width=1500,height=50,bg="orchid3")
    copyf.place(relx=0,rely=0.94)
    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    copyf1=Label(win,text="@Copyrights 2024",font=label_font,bg="orchid3",fg="black")
    copyf1.place(relx=0.42,rely=0.94)
    win.mainloop() 

def adminlogin(win):
    win.destroy()
    win=Tk()
    win.attributes('-fullscreen',True)
    win.geometry("500x500")
    f1=Frame(win,width=1500,height=60,bg="orchid3")
    f1.pack()
    f2=Frame(win,width=3500,height=60)
    label_font=font.Font(weight="bold",family="Times New Roman",size=30)
    f2=Label(win,text="LIVE CARRIERS",font=label_font,bg="orchid3",fg="black")
    f2.place(relx=0.4,rely=0.01)
    img1=ImageTk.PhotoImage(Image.open("logoimage.jpg"))
    i1=Label(win,image=img1)
    i1.place(relx=0.33,rely=0.005)
    img=ImageTk.PhotoImage(Image.open("adminloginimage.jpg"))
    canvas=Canvas(win)
    canvas.create_image(750,500,image=img)
    canvas.pack(fill="both",expand=True)
    label_font=font.Font(weight="bold",family="Microsoft yahei ui light",size=23)
    canvas.create_text(728,190,text="Sign in",fill="black",font=label_font)
    label_font=font.Font(weight="bold",family="Microsoft yahei ui light",size=11)
    username=Entry(win,bg="white",font=label_font)
    username.place(relx=0.46,rely=0.4,width=220,height=30)
    username.insert(0,'Username')
    password=Entry(win,bg="white",font=label_font)
    password.place(relx=0.46,rely=0.5,width=220,height=30)
    password.insert(0,'Password')
    b=Button(win,text="Login",bg="Green",command=lambda:admin(username.get(),password.get(),win),font=label_font)
    b.place(relx=0.46,rely=0.6,width=220,height=30)
    canvas.pack(fill="both",expand=True)
    f3=Frame(win,width=1500,height=50,bg="orchid3")
    f3.place(relx=0,rely=0.94)
    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    f4=Label(win,text="@Copyrights 2024",font=label_font,bg="orchid3",fg="black")
    f4.place(relx=0.42,rely=0.94)
    win.mainloop()

def admin(a,b,win):
    if(a=="subhani" and b=="subhani"):
        adminloginhome(win)
    else:
        print("invalid username or password") 
    
def studentdetails(data,win):
    win.destroy()
    win=Tk()
    win.geometry("500x500")
    win.attributes('-fullscreen',True)
    win.configure(bg="thistle")
    f1=Frame(win,width=1500,height=50,bg="orchid3")
    f1.pack()
    f2=Frame(win,width=3500,height=40)
    label_font=font.Font(weight="bold",family="Times New Roman",size=25)
    f2=Label(win,text="LIVE CARRIERS",font=label_font,bg="orchid3",fg="black",height=0)
    f2.place(relx=0.065,rely=0.001)
    img1=ImageTk.PhotoImage(Image.open("logoimage.jpg"))
    i1=Label(win,image=img1)
    i1.place(relx=0,rely=0)
    label_font=font.Font(weight="bold",family="Times New Roman",size=19)
    f2=Button(win,text="Home",font=label_font,bg="orchid3",fg="black")
    f2.place(relx=0.47,rely=0)
    f2=Button(win,text="Admin Login",font=label_font,bg="orchid3",fg="black",command=lambda:adminlogin(win))
    f2.place(relx=0.53,rely=0)
    f2=Button(win,text="Student Login",font=label_font,bg="orchid3",fg="black",command=lambda:studentlogin(win))
    f2.place(relx=0.65,rely=0)
    f2=Button(win,text="Staff Login",font=label_font,bg="orchid3",fg="black",command=lambda:stafflogin(win))
    f2.place(relx=0.77,rely=0)
    f2=Button(win,text="Courses",font=label_font,bg="orchid3",fg="black",command=lambda:courses(win))
    f2.place(relx=0.87,rely=0)
    f2=Button(win,text="Exit",font=label_font,bg="orchid3",fg="black",command=lambda:exit(win))
    f2.place(relx=0.95,rely=0)
    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    l1=Label(win,text="Name                   : "+data[0],font=label_font,bg="thistle").place(relx=0.35,rely=0.2)
    l2=Label(win,text="DOB                     : "+data[1],font=label_font,bg="thistle").place(relx=0.35,rely=0.3)
    l3=Label(win,text="Email_ID             : "+data[3],font=label_font,bg="thistle").place(relx=0.35,rely=0.4)
    l4=Label(win,text="Contact                : "+data[4],font=label_font,bg="thistle").place(relx=0.35,rely=0.5)
    l5=Label(win,text="Course                  : "+data[5],font=label_font,bg="thistle").place(relx=0.35,rely=0.6)
    l6=Label(win,text="Qualification        : "+data[6],font=label_font,bg="thistle").place(relx=0.35,rely=0.7)
    l7=Label(win,text="Address                 : "+data[7],font=label_font,bg="thistle").place(relx=0.35,rely=0.8)
    f3=Frame(win,width=1500,height=50,bg="orchid3")
    f3.place(relx=0,rely=0.94)
    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    f4=Label(win,text="@Copyrights 2024",font=label_font,bg="orchid3",fg="black")
    f4.place(relx=0.42,rely=0.94)
    win.mainloop() 

def studentlogin(win):
    win.destroy()
    win=Tk()
    win.attributes('-fullscreen',True)
    win.geometry("500x500")
    f1=Frame(win,width=1500,height=60,bg="orchid3")
    f1.pack()
    f2=Frame(win,width=3500,height=60)
    label_font=font.Font(weight="bold",family="Times New Roman",size=30)
    f2=Label(win,text="LIVE CARRIERS",font=label_font,bg="orchid3",fg="black")
    f2.place(relx=0.4,rely=0.01)
    img1=ImageTk.PhotoImage(Image.open("logoimage.jpg"))
    i1=Label(win,image=img1)
    i1.place(relx=0.33,rely=0.005)
    img=ImageTk.PhotoImage(Image.open("studentsigninimage.jpg"))
    canvas=Canvas(win)
    canvas.create_image(350,326,image=img)
    canvas.pack(fill="both",expand=True)
    label_font=font.Font(weight="bold",family="Microsoft yahei ui light",size=23)
    canvas.create_text(980,190,text="Sign in",fill="black",font=label_font)
    label_font=font.Font(weight="bold",family="Microsoft yahei ui light",size=11)
    username=Entry(win,bg="white",font=label_font)
    username.place(relx=0.65,rely=0.4,width=220,height=30)
    username.insert(0,'Username')
    password=Entry(win,bg="white",font=label_font)
    password.place(relx=0.65,rely=0.5,width=220,height=30)
    password.insert(0,'Password')

    def signin(win,a,b):
        connection=mysql.connect(host="localhost",user="root",password="livewire",database="subhanistudentregistration")
        cursor=connection.cursor()
        result="select * from studentregistrationtable01 where Name='"+username.get()+"'and DOB='"+password.get()+"'"
        cursor.execute(result)
        print(result)
        r=0
        for x in cursor:
            studentdetails(x,win)

    b=Button(win,text="Sign in",bg="Green",font=label_font,command=lambda:signin(win,username.get(),password.get()))
    b.place(relx=0.65,rely=0.6,width=220,height=30)
    canvas.pack(fill="both",expand=True)
    f3=Frame(win,width=1500,height=55,bg="orchid3")
    f3.place(relx=0,rely=0.93)
    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    f4=Label(win,text="@Copyrights 2024",font=label_font,bg="orchid3",fg="black")
    f4.place(relx=0.42,rely=0.94)
    win.mainloop()

def studentlist(win,a):
    win.destroy()
    win=Tk()
    win.geometry("500x500")
    win.attributes('-fullscreen',True)
    win.configure(bg="lavender")
    f1=Frame(win,width=1500,height=50,bg="orchid3")
    f1.pack()
    f2=Frame(win,width=3500,height=40)
    label_font=font.Font(weight="bold",family="Times New Roman",size=25)
    f2=Label(win,text="LIVE CARRIERS",font=label_font,bg="orchid3",fg="black",height=0)
    f2.place(relx=0.065,rely=0.001)
    img1=ImageTk.PhotoImage(Image.open("logoimage.jpg"))
    i1=Label(win,image=img1)
    i1.place(relx=0,rely=0)
    label_font=font.Font(weight="bold",family="Times New Roman",size=19)
    f2=Button(win,text="Home",font=label_font,bg="orchid3",fg="black")
    f2.place(relx=0.47,rely=0)
    f2=Button(win,text="Admin Login",font=label_font,bg="orchid3",fg="black",command=lambda:adminlogin(win))
    f2.place(relx=0.53,rely=0)
    f2=Button(win,text="Student Login",font=label_font,bg="orchid3",fg="black",command=lambda:studentlogin(win))
    f2.place(relx=0.65,rely=0)
    f2=Button(win,text="Staff Login",font=label_font,bg="orchid3",fg="black",command=lambda:stafflogin(win))
    f2.place(relx=0.77,rely=0)
    f2=Button(win,text="Courses",font=label_font,bg="orchid3",fg="black",command=lambda:courses(win))
    f2.place(relx=0.87,rely=0)
    f2=Button(win,text="Exit",font=label_font,bg="orchid3",fg="black",command=lambda:exit(win))
    f2.place(relx=0.95,rely=0)

    connection=mysql.connect(host="localhost",user="root",password="livewire",database="subhanistudentregistration")
    cursor=connection.cursor()
    result="select * from studentregistrationtable03 where Staffid='"+str(a)+"'"
    cursor.execute(result)
    r=0
    xp=0.3
    yp=0.25
    for x in cursor:
        label_font=font.Font(weight="bold",family="Times New Roman",size=20)
        l=Label(win,text="Name   :"+x[0]+"\t\t\tcourse   :"+x[6],font=label_font,bg="lavender")
        l.place(relx=xp,rely=yp)
        xp=0.3
        yp+=0.09

    f3=Frame(win,width=1500,height=50,bg="orchid3")
    f3.place(relx=0,rely=0.94)
    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    f4=Label(win,text="@Copyrights 2024",font=label_font,bg="orchid3",fg="black")
    f4.place(relx=0.42,rely=0.94)
    win.mainloop() 

def staffdetails(data,win):
    win.destroy()
    win=Tk()  
    win.geometry("500x500")
    win.attributes('-fullscreen',True)
    win.configure(bg="lightskyblue3")
    f1=Frame(win,width=1500,height=60,bg="orchid3")
    f1.pack()
    f2=Frame(win,width=3500,height=60)
    label_font=font.Font(weight="bold",family="Times New Roman",size=30)
    f2=Label(win,text="LIVE CARRIERS",font=label_font,bg="orchid3",fg="black")
    f2.place(relx=0.4,rely=0.01)
    img1=ImageTk.PhotoImage(Image.open("logoimage.jpg"))
    i1=Label(win,image=img1)
    i1.place(relx=0.33,rely=0.005)
    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    l1=Label(win,text="Name                : "+data[0],font=label_font,bg="lightskyblue3").place(relx=0.18,rely=0.25)
    l2=Label(win,text="DOB                 : "+data[1],font=label_font,bg="lightskyblue3").place(relx=0.18,rely=0.35)
    l3=Label(win,text="Gender              : "+str(data[2]),font=label_font,bg="lightskyblue3").place(relx=0.18,rely=0.45)
    l4=Label(win,text="Staff-ID             : "+str(data[3]),font=label_font,bg="lightskyblue3").place(relx=0.18,rely=0.55)
    l5=Label(win,text="Email-ID            : "+data[4],font=label_font,bg="lightskyblue3").place(relx=0.18,rely=0.65)
    l6=Label(win,text="Designation       : "+data[5],font=label_font,bg="lightskyblue3").place(relx=0.18,rely=0.75)
    l7=Label(win,text="Field                  : "+data[6],font=label_font,bg="lightskyblue3").place(relx=0.56,rely=0.25)
    l8=Label(win,text="Contact              : "+data[7],font=label_font,bg="lightskyblue3").place(relx=0.56,rely=0.35)
    l9=Label(win,text="Adhaar No          : "+data[8],font=label_font,bg="lightskyblue3").place(relx=0.56,rely=0.45)
    l10=Label(win,text="Department        : "+data[9],font=label_font,bg="lightskyblue3").place(relx=0.56,rely=0.55)
    l11=Label(win,text="Address              : "+data[10],font=label_font,bg="lightskyblue3").place(relx=0.56,rely=0.65)
    label_font=font.Font(weight="bold",family="Helvetica",size=10)
    b1=Button(win,text="Student Details",font=label_font,bg="green",command=lambda:studentlist(win,data[3]))
    b1.place(relx=0.71,rely=0.75)
    f3=Frame(win,width=1500,height=50,bg="orchid3")
    f3.place(relx=0,rely=0.94)
    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    f4=Label(win,text="@Copyrights 2024",font=label_font,bg="orchid3",fg="black")
    f4.place(relx=0.42,rely=0.94)
    win.mainloop() 

def stafflogin(win):
    win.destroy()
    win=Tk()
    win.attributes('-fullscreen',True)
    win.geometry("500x500")
    win.configure(bg="white")
    f1=Frame(win,width=1500,height=60,bg="orchid3")
    f1.pack()
    f2=Frame(win,width=3500,height=60)
    label_font=font.Font(weight="bold",family="Times New Roman",size=30)
    f2=Label(win,text="LIVE CARRIERS",font=label_font,bg="orchid3",fg="black")
    f2.place(relx=0.4,rely=0.01)
    img1=ImageTk.PhotoImage(Image.open("logoimage.jpg"))
    i1=Label(win,image=img1)
    i1.place(relx=0.33,rely=0.005)
    img=ImageTk.PhotoImage(Image.open("staffloginimage.jpg"))
    canvas=Canvas(win)
    canvas.create_image(350,326,image=img)
    label_font=font.Font(weight="bold",family="Microsoft yahei ui light",size=23)
    canvas.create_text(980,190,text="Sign in",fill="black",font=label_font)
    label_font=font.Font(weight="bold",family="Microsoft yahei ui light",size=11)
    username=Entry(win,bg="white",font=label_font)
    username.place(relx=0.65,rely=0.4,width=220,height=30)
    username.insert(0,'Username')
    password=Entry(win,bg="white",font=label_font)
    password.place(relx=0.65,rely=0.5,width=220,height=30)
    password.insert(0,'Password')

    def signin(win,a,b):
        connection=mysql.connect(host="localhost",user="root",password="livewire",database="subhanistaffregistration")
        cursor=connection.cursor()
        result="select * from staffregistrationtable03 where Name='"+username.get()+"'and DOB='"+password.get()+"'"
        cursor.execute(result)
        r=0
        for x in cursor:
            staffdetails(x,win)

    b=Button(win,text="Sign in",bg="Green",font=label_font,command=lambda:signin(win,username.get(),password.get()))
    b.place(relx=0.65,rely=0.6,width=220,height=30)
    canvas.pack(fill="both",expand=True)
    f3=Frame(win,width=1500,height=55,bg="orchid3")
    f3.place(relx=0,rely=0.93)
    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    f4=Label(win,text="@Copyrights 2024",font=label_font,bg="orchid3",fg="black")
    f4.place(relx=0.42,rely=0.94)
    win.mainloop()

def next2(win):
    win.destroy()
    win=Tk()
    win.geometry('500x500')
    win.attributes("-fullscreen",True)
    f1=Frame(win,width=1500,height=50,bg="orchid3")
    f1.pack()
    f2=Frame(win,width=3500,height=40)
    label_font=font.Font(weight="bold",family="Times New Roman",size=25)
    f2=Label(win,text="LIVE CARRIERS",font=label_font,bg="orchid3",fg="black",height=0)
    f2.place(relx=0.065,rely=0.001)
    img1=ImageTk.PhotoImage(Image.open("logoimage.jpg"))
    i1=Label(win,image=img1)
    i1.place(relx=0,rely=0)
    label_font=font.Font(weight="bold",family="Times New Roman",size=19)
    f2=Button(win,text="Home",font=label_font,bg="orchid3",fg="black")
    f2.place(relx=0.47,rely=0)
    f2=Button(win,text="Admin Login",font=label_font,bg="orchid3",fg="black",command=lambda:adminlogin(win))
    f2.place(relx=0.53,rely=0)
    f2=Button(win,text="Student Login",font=label_font,bg="orchid3",fg="black",command=lambda:studentlogin(win))
    f2.place(relx=0.65,rely=0)
    f2=Button(win,text="Staff Login",font=label_font,bg="orchid3",fg="black",command=lambda:stafflogin(win))
    f2.place(relx=0.77,rely=0)
    f2=Button(win,text="Courses",font=label_font,bg="orchid3",fg="black",command=lambda:courses(win))
    f2.place(relx=0.87,rely=0)
    f2=Button(win,text="Exit",font=label_font,bg="orchid3",fg="black",command=lambda:exit(win))
    f2.place(relx=0.95,rely=0)
    frame1=Frame(win,width=290,height=380,bg="snow1")
    frame1.place(relx=0.02,rely=0.2)
    imgf1=ImageTk.PhotoImage(Image.open("softwaretestingimg.jpg"))
    l1=Label(frame1,image=imgf1)
    l1.place(relx=0.003,rely=0.003)
    label_font=font.Font(weight="bold",family="Helvetica",size=15)
    a1=Label(frame1,text="Software Testing",font=label_font,bg="white",fg="blue")
    a1.place(relx=0.003,rely=0.69)
    label_font=font.Font(weight="bold",family="Times New Roman",size=14)
    a2=Label(frame1,text="In-centre| Online| Hybrid",font=label_font,bg="white")
    a2.place(relx=0.003,rely=0.77)
    a3=Label(frame1,text="80 Hours| Full/Part time",font=label_font,bg="white")
    a3.place(relx=0.003,rely=0.837)
    a4=Label(frame1,text="Carrer support| Placement",font=label_font,bg="white")
    a4.place(relx=0.003,rely=0.895)
    frame2=Frame(win,width=290,height=380,bg="snow1")
    frame2.place(relx=0.27,rely=0.2)
    imgf2=ImageTk.PhotoImage(Image.open("c++img.jpg"))
    l2=Label(frame2,image=imgf2)
    l2.place(relx=0.006,rely=0.004)
    label_font=font.Font(weight="bold",family="Helvetica",size=15)
    b1=Label(frame2,text="C and C++",font=label_font,bg="white",fg="blue")
    b1.place(relx=0.008,rely=0.69)
    label_font=font.Font(weight="bold",family="Times New Roman",size=14)
    b2=Label(frame2,text="In-centre| Online| Hybrid",font=label_font,bg="white")
    b2.place(relx=0.003,rely=0.77)
    b3=Label(frame2,text="64 Hours| Full/Part time",font=label_font,bg="white")
    b3.place(relx=0.003,rely=0.837)
    b4=Label(frame2,text="Carrer support| Placement",font=label_font,bg="white")
    b4.place(relx=0.003,rely=0.895)
    frame3=Frame(win,width=290,height=380,bg="snow1")
    frame3.place(relx=0.52,rely=0.2)
    imgf3=ImageTk.PhotoImage(Image.open("asp.netimg.jpg"))
    l3=Label(frame3,image=imgf3)
    l3.place(relx=0.005,rely=0.003)
    label_font=font.Font(weight="bold",family="Helvetica",size=15)
    c1=Label(frame3,text="ASP .net",font=label_font,bg="white",fg="blue")
    c1.place(relx=0.008,rely=0.69)
    label_font=font.Font(weight="bold",family="Times New Roman",size=14)
    c2=Label(frame3,text="In-centre| Online| Hybrid",font=label_font,bg="white")
    c2.place(relx=0.003,rely=0.77)
    c3=Label(frame3,text="100 Hours| Full/Part time",font=label_font,bg="white")
    c3.place(relx=0.003,rely=0.837)
    c4=Label(frame3,text="Carrer support| Placement",font=label_font,bg="white")
    c4.place(relx=0.003,rely=0.895)
    frame4=Frame(win,width=290,height=380,bg="snow1")
    frame4.place(relx=0.77,rely=0.2)
    imgf4=ImageTk.PhotoImage(Image.open("Djangoimg.jpg"))
    l4=Label(frame4,image=imgf4)
    l4.place(relx=0.005,rely=0.003)
    label_font=font.Font(weight="bold",family="Helvetica",size=15)
    d1=Label(frame4,text="Course on Django",font=label_font,bg="white",fg="blue")
    d1.place(relx=0.008,rely=0.69)
    label_font=font.Font(weight="bold",family="Times New Roman",size=14)
    d2=Label(frame4,text="In-centre| Online| Hybrid",font=label_font,bg="white")
    d2.place(relx=0.003,rely=0.77)
    d3=Label(frame4,text="56 Hours| Full/Part time",font=label_font,bg="white")
    d3.place(relx=0.003,rely=0.837)
    d4=Label(frame4,text="Carrer support| Placement",font=label_font,bg="white")
    d4.place(relx=0.003,rely=0.895)
    label_font=font.Font(weight="bold",family="Helvetica",size=12)
    b1=Button(win,text="Previous",bg="limegreen",fg="white",font=label_font,command=lambda:next1(win))
    b1.place(relx=0.92,rely=0.8)
    label_font=font.Font(weight="bold",family="Times New Roman",size=15)
    copyf=Frame(win,width=1500,height=50,bg="orchid3")
    copyf.place(relx=0,rely=0.94) 
    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    copyf1=Label(win,text="@Copyrights 2024",font=label_font,bg="orchid3",fg="black")
    copyf1.place(relx=0.42,rely=0.94)
    win.mainloop()  

def next1(win):
    win.destroy()
    win=Tk()
    win.geometry('500x500')
    win.attributes("-fullscreen",True)
    f1=Frame(win,width=1500,height=50,bg="orchid3")
    f1.pack()
    f2=Frame(win,width=3500,height=40)
    label_font=font.Font(weight="bold",family="Times New Roman",size=25)
    f2=Label(win,text="LIVE CARRIERS",font=label_font,bg="orchid3",fg="black",height=0)
    f2.place(relx=0.065,rely=0.001)
    img1=ImageTk.PhotoImage(Image.open("logoimage.jpg"))
    i1=Label(win,image=img1)
    i1.place(relx=0,rely=0)
    label_font=font.Font(weight="bold",family="Times New Roman",size=19)
    f2=Button(win,text="Home",font=label_font,bg="orchid3",fg="black")
    f2.place(relx=0.47,rely=0)
    f2=Button(win,text="Admin Login",font=label_font,bg="orchid3",fg="black",command=lambda:adminlogin(win))
    f2.place(relx=0.53,rely=0)
    f2=Button(win,text="Student Login",font=label_font,bg="orchid3",fg="black",command=lambda:studentlogin(win))
    f2.place(relx=0.65,rely=0)
    f2=Button(win,text="Staff Login",font=label_font,bg="orchid3",fg="black")
    f2.place(relx=0.77,rely=0)
    f2=Button(win,text="Courses",font=label_font,bg="orchid3",fg="black")
    f2.place(relx=0.87,rely=0)
    f2=Button(win,text="Exit",font=label_font,bg="orchid3",fg="black",command=lambda:exit(win))
    f2.place(relx=0.95,rely=0)
    frame1=Frame(win,width=290,height=380,bg="snow1")
    frame1.place(relx=0.02,rely=0.2)
    imgf1=ImageTk.PhotoImage(Image.open("tallyimg.jpg"))
    l1=Label(frame1,image=imgf1)
    l1.place(relx=0.003,rely=0.003)
    label_font=font.Font(weight="bold",family="Helvetica",size=15)
    a1=Label(frame1,text="Tally Prime",font=label_font,bg="white",fg="blue")
    a1.place(relx=0.003,rely=0.69)
    label_font=font.Font(weight="bold",family="Times New Roman",size=14)
    a2=Label(frame1,text="In-centre| Online| Hybrid",font=label_font,bg="white")
    a2.place(relx=0.003,rely=0.77)
    a3=Label(frame1,text="150 Hours| Full/Part time",font=label_font,bg="white")
    a3.place(relx=0.003,rely=0.837)
    a4=Label(frame1,text="Carrer support| Placement",font=label_font,bg="white")
    a4.place(relx=0.003,rely=0.895)
    frame2=Frame(win,width=290,height=380,bg="snow1")
    frame2.place(relx=0.27,rely=0.2)
    imgf2=ImageTk.PhotoImage(Image.open("javaimg.jpg"))
    l2=Label(frame2,image=imgf2)
    l2.place(relx=0.006,rely=0.004)
    label_font=font.Font(weight="bold",family="Helvetica",size=15)
    b1=Label(frame2,text="Advanced Java",font=label_font,bg="white",fg="blue")
    b1.place(relx=0.008,rely=0.69)
    label_font=font.Font(weight="bold",family="Times New Roman",size=14)
    b2=Label(frame2,text="In-centre| Online| Hybrid",font=label_font,bg="white")
    b2.place(relx=0.003,rely=0.77)
    b3=Label(frame2,text="120 Hours| Full/Part time",font=label_font,bg="white")
    b3.place(relx=0.003,rely=0.837)
    b4=Label(frame2,text="Carrer support| Placement",font=label_font,bg="white")
    b4.place(relx=0.003,rely=0.895)
    frame3=Frame(win,width=290,height=380,bg="snow1")
    frame3.place(relx=0.52,rely=0.2)
    imgf3=ImageTk.PhotoImage(Image.open("statisticsimg.jpg"))
    l3=Label(frame3,image=imgf3)
    l3.place(relx=0.005,rely=0.003)
    label_font=font.Font(weight="bold",family="Helvetica",size=15)
    c1=Label(frame3,text="Statistics",font=label_font,bg="white",fg="blue")
    c1.place(relx=0.008,rely=0.69)
    label_font=font.Font(weight="bold",family="Times New Roman",size=14)
    c2=Label(frame3,text="In-centre| Online| Hybrid",font=label_font,bg="white")
    c2.place(relx=0.003,rely=0.77)
    c3=Label(frame3,text="40 Hours| Full/Part time",font=label_font,bg="white")
    c3.place(relx=0.003,rely=0.837)
    c4=Label(frame3,text="Carrer support| Placement",font=label_font,bg="white")
    c4.place(relx=0.003,rely=0.895)
    frame4=Frame(win,width=290,height=380,bg="snow1")
    frame4.place(relx=0.77,rely=0.2)
    imgf4=ImageTk.PhotoImage(Image.open("blockchainimg.jpg"))
    l4=Label(frame4,image=imgf4)
    l4.place(relx=0.005,rely=0.003)
    label_font=font.Font(weight="bold",family="Helvetica",size=15)
    d1=Label(frame4,text="Blockchain Technology",font=label_font,bg="white",fg="blue")
    d1.place(relx=0.008,rely=0.69)
    label_font=font.Font(weight="bold",family="Times New Roman",size=14)
    d2=Label(frame4,text="In-centre| Online| Hybrid",font=label_font,bg="white")
    d2.place(relx=0.003,rely=0.77)
    d3=Label(frame4,text="48 Hours| Full/Part time",font=label_font,bg="white")
    d3.place(relx=0.003,rely=0.837)
    d4=Label(frame4,text="Carrer support| Placement",font=label_font,bg="white")
    d4.place(relx=0.003,rely=0.895)
    label_font=font.Font(weight="bold",family="Helvetica",size=12)
    b=Button(win,text="Next",bg="limegreen",fg="white",font=label_font,command=lambda:next2(win))
    b.place(relx=0.95,rely=0.8)
    b1=Button(win,text="Previous",bg="limegreen",fg="white",font=label_font,command=lambda:next(win))
    b1.place(relx=0.87,rely=0.8)
    label_font=font.Font(weight="bold",family="Times New Roman",size=15)
    copyf=Frame(win,width=1500,height=50,bg="orchid3")
    copyf.place(relx=0,rely=0.94) 
    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    copyf1=Label(win,text="@Copyrights 2024",font=label_font,bg="orchid3",fg="black")
    copyf1.place(relx=0.42,rely=0.94)
    win.mainloop()  

def next(win):
    win.destroy()
    win=Tk()
    win.geometry('500x500')
    win.attributes("-fullscreen",True)
    f1=Frame(win,width=1500,height=50,bg="orchid3")
    f1.pack()
    f2=Frame(win,width=3500,height=40)
    label_font=font.Font(weight="bold",family="Times New Roman",size=25)
    f2=Label(win,text="LIVE CARRIERS",font=label_font,bg="orchid3",fg="black",height=0)
    f2.place(relx=0.065,rely=0.001)
    img1=ImageTk.PhotoImage(Image.open("logoimage.jpg"))
    i1=Label(win,image=img1)
    i1.place(relx=0,rely=0)
    label_font=font.Font(weight="bold",family="Times New Roman",size=19)
    f2=Button(win,text="Home",font=label_font,bg="orchid3",fg="black")
    f2.place(relx=0.47,rely=0)
    f2=Button(win,text="Admin Login",font=label_font,bg="orchid3",fg="black",command=lambda:adminlogin(win))
    f2.place(relx=0.53,rely=0)
    f2=Button(win,text="Student Login",font=label_font,bg="orchid3",fg="black",command=lambda:studentlogin(win))
    f2.place(relx=0.65,rely=0)
    f2=Button(win,text="Staff Login",font=label_font,bg="orchid3",fg="black",command=lambda:stafflogin(win))
    f2.place(relx=0.77,rely=0)
    f2=Button(win,text="Courses",font=label_font,bg="orchid3",fg="black",command=lambda:courses(win))
    f2.place(relx=0.87,rely=0)
    f2=Button(win,text="Exit",font=label_font,bg="orchid3",fg="black",command=lambda:exit(win))
    f2.place(relx=0.95,rely=0)
    frame1=Frame(win,width=290,height=380,bg="snow1")
    frame1.place(relx=0.03,rely=0.2)
    imgf1=ImageTk.PhotoImage(Image.open("Datascienceimg.jpg"))
    l1=Label(frame1,image=imgf1)
    l1.place(relx=0.003,rely=0.003)
    label_font=font.Font(weight="bold",family="Helvetica",size=15)
    a1=Label(frame1,text="Data Science",font=label_font,bg="white",fg="blue")
    a1.place(relx=0.003,rely=0.69)
    label_font=font.Font(weight="bold",family="Times New Roman",size=14)
    a2=Label(frame1,text="In-centre| Online| Hybrid",font=label_font,bg="white")
    a2.place(relx=0.003,rely=0.77)
    a3=Label(frame1,text="150 Hours| Full/Part time",font=label_font,bg="white")
    a3.place(relx=0.003,rely=0.837)
    a4=Label(frame1,text="Carrer support| Placement",font=label_font,bg="white")
    a4.place(relx=0.003,rely=0.895)
    frame2=Frame(win,width=290,height=380,bg="snow1")
    frame2.place(relx=0.28,rely=0.2)
    imgf2=ImageTk.PhotoImage(Image.open("microsoftimg.jpg"))
    l2=Label(frame2,image=imgf2)
    l2.place(relx=0,rely=0.004)
    label_font=font.Font(weight="bold",family="Helvetica",size=15)
    b1=Label(frame2,text="Microsoft Office",font=label_font,bg="white",fg="blue")
    b1.place(relx=0.008,rely=0.69)
    label_font=font.Font(weight="bold",family="Times New Roman",size=14)
    b2=Label(frame2,text="In-centre| Online| Hybrid",font=label_font,bg="white")
    b2.place(relx=0.003,rely=0.77)
    b3=Label(frame2,text="60 Hours| Full/Part time",font=label_font,bg="white")
    b3.place(relx=0.003,rely=0.837)
    b4=Label(frame2,text="Carrer support| Placement",font=label_font,bg="white")
    b4.place(relx=0.003,rely=0.895)
    frame3=Frame(win,width=290,height=380,bg="snow1")
    frame3.place(relx=0.53,rely=0.2)
    imgf3=ImageTk.PhotoImage(Image.open("roboticimg.jpg"))
    l3=Label(frame3,image=imgf3)
    l3.place(relx=0.005,rely=0.003)
    label_font=font.Font(weight="bold",family="Helvetica",size=15)
    c1=Label(frame3,text="Course on Robotics",font=label_font,bg="white",fg="blue")
    c1.place(relx=0.008,rely=0.69)
    label_font=font.Font(weight="bold",family="Times New Roman",size=14)
    c2=Label(frame3,text="In-centre| Online| Hybrid",font=label_font,bg="white")
    c2.place(relx=0.003,rely=0.77)
    c3=Label(frame3,text="40 Hours| Full/Part time",font=label_font,bg="white")
    c3.place(relx=0.003,rely=0.837)
    c4=Label(frame3,text="Carrer support| Placement",font=label_font,bg="white")
    c4.place(relx=0.003,rely=0.895)
    frame4=Frame(win,width=290,height=380,bg="snow1")
    frame4.place(relx=0.78,rely=0.2)
    imgf4=ImageTk.PhotoImage(Image.open("excelimg.jpg"))
    l4=Label(frame4,image=imgf4)
    l4.place(relx=0.005,rely=0.003)
    label_font=font.Font(weight="bold",family="Helvetica",size=15)
    d1=Label(frame4,text="Advanced Excel",font=label_font,bg="white",fg="blue")
    d1.place(relx=0.008,rely=0.69)
    label_font=font.Font(weight="bold",family="Times New Roman",size=14)
    d2=Label(frame4,text="In-centre| Online| Hybrid",font=label_font,bg="white")
    d2.place(relx=0.003,rely=0.77)
    d3=Label(frame4,text="50 Hours| Full/Part time",font=label_font,bg="white")
    d3.place(relx=0.003,rely=0.837)
    d4=Label(frame4,text="Carrer support| Placement",font=label_font,bg="white")
    d4.place(relx=0.003,rely=0.895)
    label_font=font.Font(weight="bold",family="Helvetica",size=12)
    b=Button(win,text="Next",bg="limegreen",fg="white",font=label_font,command=lambda:next1(win))
    b.place(relx=0.95,rely=0.8)
    b1=Button(win,text="Previous",bg="limegreen",fg="white",font=label_font,command=lambda:courses(win))
    b1.place(relx=0.87,rely=0.8)
    label_font=font.Font(weight="bold",family="Times New Roman",size=15)
    copyf=Frame(win,width=1500,height=50,bg="orchid3")
    copyf.place(relx=0,rely=0.94) 
    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    copyf1=Label(win,text="@Copyrights 2024",font=label_font,bg="orchid3",fg="black")
    copyf1.place(relx=0.42,rely=0.94)
    win.mainloop()  

def courses(win):
    win.destroy()
    win=Tk()
    win.geometry('500x500')
    win.attributes("-fullscreen",True)
    f1=Frame(win,width=1500,height=50,bg="orchid3")
    f1.pack()
    f2=Frame(win,width=3500,height=40)
    label_font=font.Font(weight="bold",family="Times New Roman",size=25)
    f2=Label(win,text="LIVE CARRIERS",font=label_font,bg="orchid3",fg="black",height=0)
    f2.place(relx=0.065,rely=0.001)
    img1=ImageTk.PhotoImage(Image.open("logoimage.jpg"))
    i1=Label(win,image=img1)
    i1.place(relx=0,rely=0)
    label_font=font.Font(weight="bold",family="Times New Roman",size=19)
    f2=Button(win,text="Home",font=label_font,bg="orchid3",fg="black")
    f2.place(relx=0.47,rely=0)
    f2=Button(win,text="Admin Login",font=label_font,bg="orchid3",fg="black",command=lambda:adminlogin(win))
    f2.place(relx=0.53,rely=0)
    f2=Button(win,text="Student Login",font=label_font,bg="orchid3",fg="black",command=lambda:studentlogin(win))
    f2.place(relx=0.65,rely=0)
    f2=Button(win,text="Staff Login",font=label_font,bg="orchid3",fg="black",command=lambda:stafflogin(win))
    f2.place(relx=0.77,rely=0)
    f2=Button(win,text="Courses",font=label_font,bg="orchid3",fg="black",command=lambda:courses(win))
    f2.place(relx=0.87,rely=0)
    f2=Button(win,text="Exit",font=label_font,bg="orchid3",fg="black",command=lambda:exit(win))
    f2.place(relx=0.95,rely=0)
    frame1=Frame(win,width=260,height=380,bg="snow1")
    frame1.place(relx=0.03,rely=0.2)
    imgf1=ImageTk.PhotoImage(Image.open("phythonimage.png"))
    l1=Label(frame1,image=imgf1)
    l1.place(relx=0.003,rely=0.003)
    label_font=font.Font(weight="bold",family="Helvetica",size=15)
    a1=Label(frame1,text="Course on Python",font=label_font,bg="white",fg="blue")
    a1.place(relx=0.003,rely=0.69)
    label_font=font.Font(weight="bold",family="Times New Roman",size=14)
    a2=Label(frame1,text="In-centre| Online| Hybrid",font=label_font,bg="white")
    a2.place(relx=0.003,rely=0.77)
    a3=Label(frame1,text="60 Hours| Full/Part time",font=label_font,bg="white")
    a3.place(relx=0.003,rely=0.837)
    a4=Label(frame1,text="Carrer support| Placement",font=label_font,bg="white")
    a4.place(relx=0.003,rely=0.895)
    frame2=Frame(win,width=290,height=380,bg="snow1")
    frame2.place(relx=0.27,rely=0.2)
    imgf2=ImageTk.PhotoImage(Image.open("mlimage.png"))
    l2=Label(frame2,image=imgf2)
    l2.place(relx=0.008,rely=0.004)
    label_font=font.Font(weight="bold",family="Helvetica",size=15)
    b1=Label(frame2,text="Course on Machine Learning",font=label_font,bg="white",fg="blue")
    b1.place(relx=0.008,rely=0.69)
    label_font=font.Font(weight="bold",family="Times New Roman",size=14)
    b2=Label(frame2,text="In-centre| Online| Hybrid",font=label_font,bg="white")
    b2.place(relx=0.003,rely=0.77)
    b3=Label(frame2,text="250 Hours| Full/Part time",font=label_font,bg="white")
    b3.place(relx=0.003,rely=0.837)
    b4=Label(frame2,text="Carrer support| Placement",font=label_font,bg="white")
    b4.place(relx=0.003,rely=0.895)
    frame3=Frame(win,width=290,height=380,bg="snow1")
    frame3.place(relx=0.53,rely=0.2)
    imgf3=ImageTk.PhotoImage(Image.open("aiimage.jpg"))
    l3=Label(frame3,image=imgf3)
    l3.place(relx=0.005,rely=0.003)
    label_font=font.Font(weight="bold",family="Helvetica",size=15)
    c1=Label(frame3,text="Artificical Intelligence",font=label_font,bg="white",fg="blue")
    c1.place(relx=0.008,rely=0.69)
    label_font=font.Font(weight="bold",family="Times New Roman",size=14)
    c2=Label(frame3,text="In-centre| Online| Hybrid",font=label_font,bg="white")
    c2.place(relx=0.003,rely=0.77)
    c3=Label(frame3,text="180 Hours| Full/Part time",font=label_font,bg="white")
    c3.place(relx=0.003,rely=0.837)
    c4=Label(frame3,text="Carrer support| Placement",font=label_font,bg="white")
    c4.place(relx=0.003,rely=0.895)
    frame4=Frame(win,width=280,height=380,bg="snow1")
    frame4.place(relx=0.78,rely=0.2)
    imgf4=ImageTk.PhotoImage(Image.open("fullstackimage.jpg"))
    l4=Label(frame4,image=imgf4)
    l4.place(relx=0.005,rely=0.003)
    label_font=font.Font(weight="bold",family="Helvetica",size=15)
    d1=Label(frame4,text="FullStack Development",font=label_font,bg="white",fg="blue")
    d1.place(relx=0.008,rely=0.69)
    label_font=font.Font(weight="bold",family="Times New Roman",size=14)
    d2=Label(frame4,text="In-centre| Online| Hybrid",font=label_font,bg="white")
    d2.place(relx=0.003,rely=0.77)
    d3=Label(frame4,text="160 Hours| Full/Part time",font=label_font,bg="white")
    d3.place(relx=0.003,rely=0.837)
    d4=Label(frame4,text="Carrer support| Placement",font=label_font,bg="white")
    d4.place(relx=0.003,rely=0.895)
    label_font=font.Font(weight="bold",family="Helvetica",size=12)
    b=Button(win,text="Next",bg="limegreen",fg="white",font=label_font,command=lambda:next(win))
    b.place(relx=0.95,rely=0.8)
    label_font=font.Font(weight="bold",family="Times New Roman",size=15)
    copyf=Frame(win,width=1500,height=50,bg="orchid3")
    copyf.place(relx=0,rely=0.94) 
    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    copyf1=Label(win,text="@Copyrights 2024",font=label_font,bg="orchid3",fg="black")
    copyf1.place(relx=0.42,rely=0.94)
    win.mainloop()  

def exit(win):
    answer=messagebox.askquestion("exit","Do you want to exit the application?")
    if(answer=="yes"):
        win.destroy()

def home():
    win=Tk()
    win.geometry("500x500")
    win.attributes('-fullscreen',True)
    f1=Frame(win,width=1500,height=60,bg="orchid3")
    f1.pack()
    f2=Frame(win,width=3500,height=60)
    label_font=font.Font(weight="bold",family="Times New Roman",size=30)
    f2=Label(win,text="LIVE CARRIERS",font=label_font,bg="orchid3",fg="black")
    f2.place(relx=0.4,rely=0.01)
    img1=ImageTk.PhotoImage(Image.open("logoimage.jpg"))
    i1=Label(win,image=img1)
    i1.place(relx=0.33,rely=0.005)
    img=ImageTk.PhotoImage(Image.open("homepageimage.jpg"))
    canvas=Canvas(win)
    canvas.create_image(830,292,image=img)
    label_font=font.Font(weight="bold",family="Times New Roman",size=30)
    canvas.create_text(800,300,text="welcome to Live Carriers",fill="white",font=label_font)
    canvas.pack(fill="both",expand=True)
    label_font=font.Font(weight="bold",family="Tahoma",size=15)
    b=Button(win,text="Home",bg="Black",fg="white",width=12,height=0,font=label_font)
    b.place(relx=0.03,rely=0.20)
    b1=Button(win,text="Admin Login",bg="Black",fg="white",width=12,height=0,font=label_font,command=lambda:adminlogin(win))
    b1.place(relx=0.03,rely=0.30)
    b2=Button(win,text="Student Login",bg="Black",fg="white",width=12,height=0,font=label_font,command=lambda:studentlogin(win))
    b2.place(relx=0.03,rely=0.40)
    b3=Button(win,text="Staff Login",bg="Black",fg="white",width=12,height=0,font=label_font,command=lambda:stafflogin(win))
    b3.place(relx=0.03,rely=0.50)
    b4=Button(win,text="Courses",bg="Black",fg="white",width=12,height=0,font=label_font,command=lambda:courses(win))
    b4.place(relx=0.03,rely=0.60)
    b5=Button(win,text="Exit",bg="Black",fg="white",width=12,height=0,font=label_font,command=lambda:exit(win))
    b5.place(relx=0.03,rely=0.70)
    f3=Frame(win,width=1500,height=60,bg="orchid3")
    f3.place(relx=0,rely=0.93)
    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    f4=Label(win,text="@Copyrights 2024",font=label_font,bg="orchid3",fg="black")
    f4.place(relx=0.42,rely=0.94)
    win.mainloop() 
home() 

