from tkinter import *
from tkinter import ttk,font,messagebox
from PIL import ImageTk,Image


     
def customerlog(win):
    win.destroy()
    win=Tk()
    win.geometry("500x500")
    win.attributes('-fullscreen',True)
    f=Frame(win,width=1500,height=50,bg="blue")
    f.pack()
    frame1=Frame(win,width=400,height=250,bg="pink")
    frame1.place(relx=0.35,rely=0.25)
    
    label_font=font.Font(weight="bold",family="Times New Roman",size=30)
    f1=Label(win,text="HDFC Bank",font=label_font,bg="blue",fg="white")
    f1.place(relx=0.40,rely=0.5)
    f1.pack()
    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    b2=Label(win,text="Customer Login",bg="green",fg="white",font=label_font)
    b2.place(relx=0.42,rely=0.15)

    label_font=font.Font(win,weight="bold",family="Times New Roman",size=15)
    l=Label(win,text="Customer ID",font=label_font).place(relx=0.37,rely=0.35)
    l=Label(win,text="Password",font=label_font).place(relx=0.38,rely=0.45)
    e1=Entry(win)
    e1.place(relx=0.49,rely=0.35,width=150,height=30)
    e2=Entry(win)
    e2.place(relx=0.49,rely=0.45,width=150,height=30)

    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    b=Button(win,text="Login",bg="green",font=label_font)
    b.place(relx=0.50,rely=0.63)
    
    f2=Frame(win,width=1500,height=50,bg="blue")
    label_font=font.Font(weight="bold",family="Times New Roman",size=30)
    f2=Label(win,text="@Copyrights 2024",font=label_font,bg="blue",fg="white")
    f2.pack()
    f2.place(relx=0.42,rely=0.90)
    win.mainloop()

def custreg(win):
    win.destroy()
    win=Tk()
    win.attributes('-fullscreen',True)
    win.geometry("500x500")
    frame=Frame(win,width=1500,height=50,bg="blue")
    frame.pack()
    frame1=Frame(win,width=400,height=380,bg="pink")
    frame1.place(relx=0.36,rely=0.25)
    f=Frame(win,width=1500,height=500,bg="blue")
    label_font=font.Font(weight="bold",family="Times New Roman",size=30)
    f=Label(win,text="HDFC Bank",font=label_font,bg="blue",fg="white")
    f.place(relx=0.40,rely=0.5)
    f.pack()

    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    b=Label(win,text="Customer Registration",bg="green",fg="white",font=label_font)
    b.place(relx=0.40,rely=0.16)

    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    l1=Label(win,text="Name",font=label_font).place(relx=0.38,rely=0.29)
    l2=Label(win,text="Aadhar No",font=label_font).place(relx=0.38,rely=0.39)
    l3=Label(win,text="Pan No",font=label_font).place(relx=0.38,rely=0.49)
    l4=Label(win,text="Contact",font=label_font).place(relx=0.38,rely=0.59)
    l4=Label(win,text="Contact",font=label_font).place(relx=0.36,rely=0.56)
    l5=Label(win,text="Email ID",font=label_font).place(relx=0.36,rely=0.66)
    l6=Label(win,text="Address",font=label_font).place(relx=0.36,rely=0.76)
    e1=Entry(win)
    e1.place(relx=0.50,rely=0.29,width=150,height=30)
    e2=Entry(win)
    e2.place(relx=0.50,rely=0.39,width=150,height=30)
    e3=Entry(win)
    e3.place(relx=0.50,rely=0.49,width=150,height=30)
    e4=Entry(win)
    e4.place(relx=0.50,rely=0.59,width=150,height=30)
    e4=Entry(win)
    e4.place(relx=0.52,rely=0.55,width=150,height=30)
    e5=Entry(win)
    e5.place(relx=0.52,rely=0.65,width=150,height=30)
    e6=Entry(win)
    e6.place(relx=0.52,rely=0.75,width=150,height=30)

    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    b=Button(win,text="Register",bg="green",fg="white",font=label_font,command=lambda:custreg(e1.get(),e2.get(),e3.get(),e4.get()))
    b.place(relx=0.50,rely=0.80)
    f2=Frame(win,width=1500,height=50,bg="blue")
    label_font=font.Font(weight="bold",family="Times New Roman",size=30)
    f2=Label(win,text="@Copyrights 2024",font=label_font,bg="blue",fg="white")
    f2.pack()
    f2.place(relx=0.40,rely=0.93)
    win.mainloop()
 
def adminlog(win):
    win.destroy()
    win=Tk()
    win.attributes('-fullscreen',True)
    win.geometry("500x500")
    frame=Frame(win,width=1500,height=50,bg="blue")
    frame.pack()
    
    frame1=Frame(win,width=400,height=500,bg="pink")
    frame1.place(relx=0.35,rely=0.20)

    label_font=font.Font(weight="bold",family="Times New Roman",size=30)
    f=Label(win,text="HDFC Bank",font=label_font,bg="blue",fg="white")
    f.place(relx=0.40,rely=0.5)
    f.pack()

    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    b=Label(win,text="Admin Login",bg="green",fg="white",font=label_font)
    b.place(relx=0.44,rely=0.14)
  
    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    l1=Label(win,text="UserName",font=label_font).place(relx=0.36,rely=0.26)
    l2=Label(win,text="Password",font=label_font).place(relx=0.36,rely=0.36)
   
    e1=Entry(win)
    e1.place(relx=0.52,rely=0.25,width=150,height=30)
    e2=Entry(win)
    e2.place(relx=0.52,rely=0.35,width=150,height=30)
    e3=Entry(win)
    e3.place(relx=0.52,rely=0.45,width=150,height=30)
    

    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    b=Button(win,text="Login",bg="green",font=label_font,command=lambda:adminlog(e1.get(),e2.get(),e3.get(),e4.get(),e5.get(),e6.get()))
    b.place(relx=0.52,rely=0.87)
    f2=Frame(win,width=1500,height=50,bg="blue")
    label_font=font.Font(weight="bold",family="Times New Roman",size=30)
    f2=Label(win,text="@Copyrights 2024",font=label_font,bg="blue",fg="white")
    f2.pack()
    f2.place(relx=0.45,rely=0.95)
    win.mainloop()

def home():
    win=Tk()
    win.geometry("500x500")
    win.attributes('-fullscreen',True)
    frame=Frame(win,width=1500,height=50,bg="blue")
    frame.pack()
    f=Frame(win,width=1500,height=50,bg="blue")
    label_font=font.Font(weight="bold",family="Times New Roman",size=30)
    f=Label(win,text="HDFC Bank",font=label_font,bg="blue",fg="white")
    f.place(relx=0.30,rely=0.1)
    f.pack()
    f1=Frame(win,width=1000,height=50)
    f1.pack()
    f1.place(relx=0.39,rely=0.2)
    img=ImageTk.PhotoImage(Image.open("bank2.jpg"))
    l=Label(f1,image=img)
    l.pack()
    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    s="""A bank is a financial institution that accepts deposits from the public and creates a demand deposit 
     while simultaneously making loans. 
     A bank is a financial institution that is licensed to accept checking and savings deposits and make loans. 
     Lending activities can be directly performed by the bank or indirectly through capital markets."""
    l1=Label(win,text=s,font=label_font)
    l1.place(relx=0.01,rely=0.45)
    b=Button(win,text="Customer Registration",bg="green",fg="white",font=label_font,command=lambda:custreg(win))
    b.place(relx=0.15,rely=0.70)
    b1=Button(win,text="Admin Login",bg="green",fg="white",font=label_font,command=lambda:adminlog(win))
    b1.place(relx=0.45,rely=0.70)
    b2=Button(win,text="Customer Login",bg="green",fg="white",font=label_font,command=lambda:customerlog(win))
    b2.place(relx=0.65,rely=0.70)
    f2=Frame(win,width=1500,height=50,bg="blue")
    label_font=font.Font(weight="bold",family="Times New Roman",size=30)
    f2=Label(win,text="@Copyrights 2024",font=label_font,bg="blue",fg="white")
    f2.pack()
    f2.place(relx=0.40,rely=0.90)
    win.mainloop()
home()